# description: Create a tag for a GIT repository
# Note: 
#  - shared/common code 
#  - This workflow can be called from other workflows.
name: Check GO code

on:
  workflow_call:

jobs:
  tag-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Important! To fetch all tags
                          # fetch full git history - mandatory when using some git commands like `git tag`

      - name: Get current version from VERSION file
        id: get_current_version
        run: |
          if [ ! -f VERSION ]; then
            echo "VERSION file does not exist!"
            exit 1
          fi
          version=$(cat VERSION) # Or parse go.mod if you prefer
          echo "version=$version" >> $GITHUB_OUTPUT


      - name: Get latest git tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT

      - name: Decide if tagging is needed
        id: should_tag
        run: |
          if [ -z "${{ steps.get_latest_tag.outputs.latest_tag }}" ]; then
            echo "No tags found, will create initial tag."
            echo "tag_needed=true" >> $GITHUB_OUTPUT
          elif [ "${{ steps.get_latest_tag.outputs.latest_tag }}" != "v${{ steps.get_current_version.outputs.version }}" ]; then
            echo "Version changed, will create new tag."
            echo "tag_needed=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged, skipping tag."
            echo "tag_needed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.should_tag.outputs.tag_needed == 'true'
        env:
          TAG: v${{ steps.get_current_version.outputs.version }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag -a $TAG -m "Release $TAG"
          git push origin $TAG
