# description: check that the code and of a Go project
# Note: 
#  - shared/common piece of code to 
#  - This workflow can be called from other workflows.
name: Check GO code

on:
  workflow_call:

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - name: Do the checks
        run: |
          # do a static analysis of the code recursively from the current directory
          go vet ./...
