# description: check that the code and of a Go project
# Note: 
#  - shared/common piece of code to 
#  - This workflow can be called from other workflows.
name: Check GO code

on:
  workflow_call:
    inputs:
      go-version:
        description: 'The version of Go to install'
        required: true
        type: string

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Install specified Go version
        uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Do the checks
        run: |
          # display go version
          go version
          # display folder
          pwd
          # display content
          ls -ial go.mod
          # find and run tests recursively from the current directory
          go test -v ./...
